# Generated by Django 3.2.6 on 2021-08-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='PhoneNumber',
        ),
    ]
