# Generated by Django 3.2.6 on 2021-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Re_Password',
            field=models.CharField(max_length=150),
        ),
    ]
