# Generated by Django 3.2.6 on 2021-08-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_re_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Re_Password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
