# Generated by Django 3.2.6 on 2021-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Re_Password',
        ),
    ]
